// Code generated by cmd/build/main.go; DO NOT EDIT.
package main

import (
	"github.com/faanross/spinnekop/internal/models"
)

var embeddedAgentConfig = models.DNSRequest{
	Header:   Header,
	Question: Question,
	Resolver: Resolver,
	Answers:  Answers,
}

var Header = models.Header{
	ID:                 54321,
	QR:                 true,
	OpCode:             "QUERY",
	Authoritative:      false,
	Truncated:          false,
	RecursionDesired:   true,
	RecursionAvailable: true,
	Z:                  6,
	RCode:              0,
}

var Question = models.Question{
	Name:        "data.malicious.com.",
	Type:        "TXT",
	Class:       "NO",
	StdClass:    false,
	CustomClass: 67,
}

var Resolver = models.Resolver{
	UseSystemDefaults: false,
	IP:                "1.1.1.1",
	Port:              53,
}

var Answers = []models.Answer{
	{
		Name:  "data.malicious.com.",
		Type:  "TXT",
		Class: "NO",
		TTL:   300,
		Data:  "48656c6c6f20576f726c64212048657820656e636f646564206461746120666f722074657374696e6720444e53207475a3bd656c696e672e2054686973206973206120636f6d6d6f6e20746563686e69717565207573656420666f7220646174612065786663696c7472617465696f6e2e77a4",
	},
}

// getEmbeddedAgentConfig is called by the agent's main.go to retrieve this configuration.
func getEmbeddedAgentConfig() models.DNSRequest {
	return embeddedAgentConfig
}
